package com.ssrr.domain.yahoo;

import com.fasterxml.jackson.annotation.JsonProperty;

/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/


public class Fields {
	@JsonProperty("day_low")
	private String day_low;

 	public void setDay_low(String day_low) {
		this.day_low = day_low;
	}

	public String getDay_low() {
		return day_low;
	}

	@JsonProperty("day_high")
	private String day_high;

	public void setDay_high(String day_high) {
		this.day_high = day_high;
	}

	public String getDay_high() {
		return day_high;
	}

	@JsonProperty("type")
	private String type;

	public void setType(String type) {
		this.type = type;
	}

	public String getType() {
		return type;
	}

	@JsonProperty("issuer_name")
	private String issuer_name;

	public void setIssuer_name(String issuer_name) {
		this.issuer_name = issuer_name;
	}

	public String getIssuer_name() {
		return issuer_name;
	}

	@JsonProperty("symbol")
	private String symbol;

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public String getSymbol() {
		return symbol;
	}

	@JsonProperty("ts")
	private String ts;

	public void setTs(String ts) {
		this.ts = ts;
	}

	public String getTs() {
		return ts;
	}

	@JsonProperty("change")
	private String change;

	public void setChange(String change) {
		this.change = change;
	}

	public String getChange() {
		return change;
	}

	@JsonProperty("year_low")
	private String year_low;

	public void setYear_low(String year_low) {
		this.year_low = year_low;
	}

	public String getYear_low() {
		return year_low;
	}

	@JsonProperty("volume")
	private String volume;

	public void setVolume(String volume) {
		this.volume = volume;
	}

	public String getVolume() {
		return volume;
	}

	@JsonProperty("chg_percent")
	private String chg_percent;

	public void setChg_percent(String chg_percent) {
		this.chg_percent = chg_percent;
	}

	public String getChg_percent() {
		return chg_percent;
	}

	@JsonProperty("year_high")
	private String year_high;

	public void setYear_high(String year_high) {
		this.year_high = year_high;
	}

	public String getYear_high() {
		return year_high;
	}

	@JsonProperty("price")
	private String price;

	public void setPrice(String price) {
		this.price = price;
	}

	public String getPrice() {
		return price;
	}

	@JsonProperty("utctime")
	private String utctime;

	public void setUtctime(String utctime) {
		this.utctime = utctime;
	}

	public String getUtctime() {
		return utctime;
	}

	@JsonProperty("name")
	private String name;

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

}