/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ssrr.domain.yahoo;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Meta {
	@JsonProperty("type")
	private String type;

 	public void setType(String type) {
		this.type = type;
	}

	public String getType() {
		return type;
	}

	@JsonProperty("start")
	private Integer start;

 	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getStart() {
		return start;
	}

	@JsonProperty("count")
	private Integer count;

 	public void setCount(Integer count) {
		this.count = count;
	}

	public Integer getCount() {
		return count;
	}

}