/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ssrr.domain.yahoo;

import org.dozer.Mapping;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Resource {
	@JsonProperty("fields")
	private Fields fields;

 	public void setFields(Fields fields) {
		this.fields = fields;
	}

	@Mapping("fields")
	public Fields getFields() {
		return fields;
	}

	@JsonProperty("classname")
	private String classname;

 	public void setClassname(String classname) {
		this.classname = classname;
	}

	@Mapping("type")
	public String getClassname() {
		return classname;
	}

}