/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.ssrr.domain;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Resource {
	@JsonProperty("fields")
	private Fields fields;

 	public void setFields(Fields fields) {
		this.fields = fields;
	}

	public Fields getFields() {
		return fields;
	}

	@JsonProperty("classname")
	private java.lang.String classname;

 	public void setClassname(java.lang.String classname) {
		this.classname = classname;
	}

	public java.lang.String getClassname() {
		return classname;
	}

}